// src/features/mcp/McpEdit.tsx
import { ArrowLeft, FloppyDisk } from "@phosphor-icons/react";
import { useEffect, useRef, useState } from "react";
import { api } from "../../api";
import { useFeedback } from "../../app/Feedback";
import { AppSelect } from "../../components/AppSelect";
import ConfigTextEditor, { type ConfigTextEditorHandle } from "../../components/ConfigTextEditor";
import type { EditorDiagnosticSummary, McpServerSpec } from "../../types";

type Transport = "stdio" | "http";
interface KVPair { key: string; value: string; }

function recordToPairs(record: Record<string, string>): KVPair[] { return Object.entries(record).map(([key, value]) => ({ key, value })); }
function pairsToRecord(pairs: KVPair[]): Record<string, string> {
  const record: Record<string, string> = {};
  for (const pair of pairs) { const key = pair.key.trim(); if (key) record[key] = pair.value.trim(); }
  return record;
}

function PairEditor({ pairs, onChange, keyPlaceholder, valuePlaceholder }: { pairs: KVPair[]; onChange: (pairs: KVPair[]) => void; keyPlaceholder: string; valuePlaceholder: string }) {
  return <div className="space-y-2">{pairs.map((pair, index) => <div key={`${index}-${pair.key}`} className="flex gap-2"><input className="app-input mono" placeholder={keyPlaceholder} value={pair.key} onChange={(event) => onChange(pairs.map((current, currentIndex) => currentIndex === index ? { ...current, key: event.target.value } : current))} /><input className="app-input mono" placeholder={valuePlaceholder} value={pair.value} onChange={(event) => onChange(pairs.map((current, currentIndex) => currentIndex === index ? { ...current, value: event.target.value } : current))} /><button type="button" className="apple-icon-button text-[var(--danger)]" aria-label="删除此行" onClick={() => onChange(pairs.filter((_current, currentIndex) => currentIndex !== index))}>×</button></div>)}<button type="button" className="apple-inline-btn" onClick={() => onChange([...pairs, { key: "", value: "" }])}>添加一行</button></div>;
}

interface McpEditProps {
  server: McpServerSpec | null;
  create?: boolean;
  onBack: () => void;
}

export default function McpEdit({ server, create = false, onBack }: McpEditProps) {
  const feedback = useFeedback();
  const [name, setName] = useState(server?.name ?? "");
  const [transport, setTransport] = useState<Transport>(server?.url ? "http" : "stdio");
  const [command, setCommand] = useState(server?.command ?? "");
  const [argsText, setArgsText] = useState((server?.args ?? []).join("\n"));
  const [url, setUrl] = useState(server?.url ?? "");
  const [bearer, setBearer] = useState(server?.bearer_token_env_var ?? "");
  const [startupTimeout, setStartupTimeout] = useState<number | null>(server?.startup_timeout_sec ?? null);
  const [toolTimeout, setToolTimeout] = useState<number | null>(server?.tool_timeout_sec ?? null);
  const [envPairs, setEnvPairs] = useState<KVPair[]>(recordToPairs(server?.env ?? {}));
  const [headerPairs, setHeaderPairs] = useState<KVPair[]>(recordToPairs(server?.http_headers ?? {}));
  const [envHeaderPairs, setEnvHeaderPairs] = useState<KVPair[]>(recordToPairs(server?.env_http_headers ?? {}));
  const [tomlText, setTomlText] = useState("");
  const [initialToml, setInitialToml] = useState("");
  const [initialized, setInitialized] = useState(false);
  const [saving, setSaving] = useState(false);
  const [formatting, setFormatting] = useState(false);
  const [diagnostics, setDiagnostics] = useState<EditorDiagnosticSummary>({ count: 0, firstLine: null });
  const patchSeq = useRef(0);
  const parseSeq = useRef(0);
  const editorRef = useRef<ConfigTextEditorHandle>(null);

  const argsList = () => argsText.split("\n").map((line) => line.trim()).filter(Boolean);
  const formSpec = (): McpServerSpec => ({
    name: name.trim() || "server",
    enabled: server?.enabled ?? null,
    startup_timeout_sec: startupTimeout,
    tool_timeout_sec: toolTimeout,
    command: transport === "stdio" ? command.trim() || null : null,
    args: transport === "stdio" ? argsList() : [],
    env: transport === "stdio" ? pairsToRecord(envPairs) : {},
    url: transport === "http" ? url.trim() || null : null,
    bearer_token_env_var: transport === "http" ? bearer.trim() || null : null,
    http_headers: transport === "http" ? pairsToRecord(headerPairs) : {},
    env_http_headers: transport === "http" ? pairsToRecord(envHeaderPairs) : {},
  });

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      try {
        const initial = create
          ? await api.patchMcpFragment("[mcp_servers.server]\n", formSpec())
          : (await api.getMcpServerToml(server?.name ?? "")) ?? await api.patchMcpFragment(`[mcp_servers.${server?.name ?? "server"}]\n`, formSpec());
        if (!cancelled) { setTomlText(initial); setInitialToml(initial); setInitialized(true); }
      } catch (error) { if (!cancelled) feedback.error(String(error)); }
    })();
    return () => { cancelled = true; };
    // initial props are fixed for the mounted editor.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (!initialized) return;
    const seq = ++patchSeq.current;
    void api.patchMcpFragment(tomlText, formSpec()).then((next) => {
      if (seq === patchSeq.current && next !== tomlText) setTomlText(next);
    }).catch(() => undefined);
  }, [argsText, bearer, command, envHeaderPairs, envPairs, headerPairs, initialized, name, startupTimeout, toolTimeout, transport, url]);

  useEffect(() => {
    if (!initialized) return;
    const seq = ++parseSeq.current;
    void api.parseMcpFragment(tomlText).then((spec) => {
      if (seq !== parseSeq.current) return;
      if (/^[A-Za-z0-9_-]+$/.test(spec.name)) setName(spec.name);
      setTransport(spec.url ? "http" : "stdio");
      setCommand(spec.command ?? "");
      setArgsText(spec.args.join("\n"));
      setUrl(spec.url ?? "");
      setBearer(spec.bearer_token_env_var ?? "");
      setStartupTimeout(spec.startup_timeout_sec);
      setToolTimeout(spec.tool_timeout_sec);
      setEnvPairs(recordToPairs(spec.env));
      setHeaderPairs(recordToPairs(spec.http_headers));
      setEnvHeaderPairs(recordToPairs(spec.env_http_headers));
    }).catch(() => undefined);
  }, [initialized, tomlText]);

  const dirty = initialized && tomlText.replace(/\r\n/g, "\n") !== initialToml.replace(/\r\n/g, "\n");

  const formatToml = async () => {
    if (formatting || saving) return;
    setFormatting(true);
    try {
      const formatted = await api.formatToml(tomlText);
      if (formatted === tomlText) feedback.info("格式无误，无需调整"); else { setTomlText(formatted); feedback.success("片段已格式化"); }
    } catch (error) { feedback.error(`格式化失败：${String(error)}`); }
    finally { setFormatting(false); }
  };

  const save = async () => {
    if (saving) return;
    if (!/^[A-Za-z0-9_-]+$/.test(name.trim())) { feedback.error("名称只能包含字母、数字、下划线和连字符"); return; }
    if (transport === "stdio" && !command.trim()) { feedback.error("请填写启动命令"); return; }
    if (transport === "http" && !url.trim()) { feedback.error("请填写服务地址"); return; }
    if (transport === "http" && !/^https?:\/\//i.test(url.trim())) { feedback.error("服务地址必须以 http:// 或 https:// 开头"); return; }
    if (startupTimeout !== null && startupTimeout <= 0) { feedback.error("启动超时必须为正数（秒）"); return; }
    if (toolTimeout !== null && toolTimeout <= 0) { feedback.error("工具调用超时必须为正数（秒）"); return; }
    setSaving(true);
    try { await api.saveMcpServer(server?.name ?? null, formSpec(), tomlText); feedback.success("MCP 服务器已保存"); onBack(); }
    catch (error) { feedback.error(String(error)); }
    finally { setSaving(false); }
  };

  return (
    <section className="apple-edit-page mx-auto flex w-full max-w-none flex-col" onKeyDown={(event) => { if (event.ctrlKey && event.key === "Enter") void save(); }}>
      <div className="apple-page-bar apple-page-bar--roomy apple-edit-toolbar apple-edit-toolbar--header"><button type="button" className="apple-page-header apple-back-button" aria-label="返回" onClick={onBack}><ArrowLeft className="h-4 w-4 shrink-0 text-accent" weight="bold" /><span className="apple-title">{create ? "新建 MCP 服务器" : "编辑 MCP 服务器"}</span></button></div>
      <div className="apple-edit-content"><div className="apple-group p-0"><div className="apple-panel-section"><div className="field-label mb-1.5">名称</div><input className="app-input mono" maxLength={64} placeholder="例如：context7" value={name} onChange={(event) => setName(event.target.value)} /><div className="field-label mb-1.5 mt-4">传输方式</div><AppSelect value={transport} options={[{ label: "本地进程 (STDIO)", value: "stdio" as const }, { label: "远程服务 (HTTP)", value: "http" as const }]} onChange={setTransport} /><div className="mt-4">{transport === "stdio" ? <><div className="field-label mb-1.5">启动命令</div><input className="app-input mono" placeholder="例如：npx 或 C:\\tools\\server.exe" value={command} onChange={(event) => setCommand(event.target.value)} /><div className="field-label mb-1.5 mt-4">启动参数（每行一个）</div><textarea className="app-input mono min-h-20" rows={2} placeholder="每行一个参数，例如：-y" value={argsText} onChange={(event) => setArgsText(event.target.value)} /></> : <><div className="field-label mb-1.5">服务地址</div><input className="app-input mono" placeholder="https://mcp.example.com/mcp" value={url} onChange={(event) => setUrl(event.target.value)} /><div className="field-label mb-1.5 mt-4">Bearer Token 环境变量名（可选）</div><input className="app-input mono" placeholder="例如：TAVILY_API_KEY" value={bearer} onChange={(event) => setBearer(event.target.value)} /><p className="muted mt-1.5 text-xs">Codex 启动时从该环境变量读取令牌放入 Authorization 头；留空则不携带。</p></>}</div></div><details className="apple-panel-section"><summary className="field-subtitle cursor-pointer">高级选项（环境变量 / 请求头 / 超时）</summary><div className="mt-4">{transport === "stdio" ? <><div className="field-label mb-1.5">环境变量</div><PairEditor pairs={envPairs} onChange={setEnvPairs} keyPlaceholder="变量名" valuePlaceholder="值" /></> : <><div className="field-label mb-1.5">HTTP 请求头（固定值）</div><PairEditor pairs={headerPairs} onChange={setHeaderPairs} keyPlaceholder="Header 名" valuePlaceholder="值" /><div className="field-label mb-1.5 mt-4">HTTP 请求头（值取自环境变量）</div><PairEditor pairs={envHeaderPairs} onChange={setEnvHeaderPairs} keyPlaceholder="Header 名" valuePlaceholder="环境变量名" /></>}<div className="mt-4 grid gap-4 sm:grid-cols-2"><div><div className="field-label mb-1.5">启动超时（秒，可选）</div><input className="app-input" type="number" min={1} placeholder="默认 10" value={startupTimeout ?? ""} onChange={(event) => setStartupTimeout(event.target.value ? Number(event.target.value) : null)} /></div><div><div className="field-label mb-1.5">工具调用超时（秒，可选）</div><input className="app-input" type="number" min={1} placeholder="默认 60" value={toolTimeout ?? ""} onChange={(event) => setToolTimeout(event.target.value ? Number(event.target.value) : null)} /></div></div></div></details><div className="apple-panel-section"><div className="field-label mb-1.5 flex items-center gap-1.5">TOML 源码{dirty ? <span className="h-1.5 w-1.5 rounded-full bg-accent" role="img" aria-label="有未保存的改动" /> : null}</div><ConfigTextEditor ref={editorRef} value={tomlText} language="toml" placeholder="编辑 [mcp_servers.*] 片段，与上方表单双向同步。" onChange={setTomlText} onDiagnostics={setDiagnostics} /><p className="muted mt-2 text-xs">表单与 TOML 会实时同步；未显示的设置和注释会保留。</p></div></div></div>
      <div className="apple-edit-toolbar apple-edit-toolbar--footer">{diagnostics.count > 0 ? <button type="button" className="mr-auto flex min-w-0 items-center gap-1.5 rounded-lg border border-[var(--danger)]/20 bg-[var(--danger)]/10 px-2.5 py-1 text-xs chip-danger" onClick={() => editorRef.current?.focusFirstDiagnostic()}>{diagnostics.count} 个错误{diagnostics.firstLine !== null ? ` · 第 ${diagnostics.firstLine} 行` : ""}</button> : null}<button type="button" className="apple-action-button" disabled={formatting || saving} onClick={() => void formatToml()}>格式化</button><button type="button" className="apple-action-button" onClick={onBack}>取消</button><button type="button" className="apple-action-button app-button--primary" disabled={saving} onClick={() => void save()}><FloppyDisk className="h-4 w-4" weight="bold" />{saving ? "保存中…" : "保存"}</button></div>
    </section>
  );
}

// src/components/McpEdit.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { NButton, NCollapse, NCollapseItem, NDynamicInput, NInput, NInputNumber, NSelect, useMessage } from "naive-ui";
import { api } from "../api";
import type { McpServerSpec } from "../types";
import { PhArrowLeft, PhFloppyDisk, PhInfo } from "@phosphor-icons/vue";

const props = defineProps<{ server: McpServerSpec | null; create?: boolean }>();
const emit = defineEmits<{ back: [] }>();

const message = useMessage();
const creating = computed(() => props.create);

const name = ref(props.server?.name ?? "");
const transport = ref<"stdio" | "http">(props.server?.url ? "http" : "stdio");
const command = ref(props.server?.command ?? "");
const argsText = ref((props.server?.args ?? []).join("\n"));
const url = ref(props.server?.url ?? "");
const bearer = ref(props.server?.bearer_token_env_var ?? "");
const startupTimeout = ref<number | null>(props.server?.startup_timeout_sec ?? null);
const toolTimeout = ref<number | null>(props.server?.tool_timeout_sec ?? null);

interface KVPair {
  key: string;
  value: string;
}

function recordToPairs(record: Record<string, string>): KVPair[] {
  return Object.entries(record).map(([key, value]) => ({ key, value }));
}

function pairsToRecord(pairs: KVPair[]): Record<string, string> {
  const record: Record<string, string> = {};
  for (const pair of pairs) {
    const key = pair.key.trim();
    if (key) record[key] = pair.value.trim();
  }
  return record;
}

const envPairs = ref<KVPair[]>(recordToPairs(props.server?.env ?? {}));
const headerPairs = ref<KVPair[]>(recordToPairs(props.server?.http_headers ?? {}));
const envHeaderPairs = ref<KVPair[]>(recordToPairs(props.server?.env_http_headers ?? {}));

const transportOptions = [
  { label: "本地进程 (STDIO)", value: "stdio" },
  { label: "远程服务 (HTTP)", value: "http" },
];

const saving = ref(false);

function argsList(): string[] {
  return argsText.value
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);
}

async function save() {
  if (saving.value) return;
  const trimmedName = name.value.trim();
  if (!/^[A-Za-z0-9_-]+$/.test(trimmedName)) {
    message.error("名称只能包含字母、数字、下划线和连字符");
    return;
  }
  if (transport.value === "stdio" && !command.value.trim()) {
    message.error("请填写启动命令");
    return;
  }
  if (transport.value === "http") {
    if (!url.value.trim()) {
      message.error("请填写服务地址");
      return;
    }
    if (!/^https?:\/\//.test(url.value.trim())) {
      message.error("服务地址必须以 http:// 或 https:// 开头");
      return;
    }
  }
  if (startupTimeout.value !== null && startupTimeout.value <= 0) {
    message.error("启动超时必须为正数（秒）");
    return;
  }
  if (toolTimeout.value !== null && toolTimeout.value <= 0) {
    message.error("工具调用超时必须为正数（秒）");
    return;
  }

  saving.value = true;
  try {
    // 只提交当前传输类型的建模字段；表单未涵盖的键（tools.*、cwd 等）由后端原样保留
    const spec: McpServerSpec = {
      name: trimmedName,
      enabled: props.server?.enabled ?? null,
      startup_timeout_sec: startupTimeout.value,
      tool_timeout_sec: toolTimeout.value,
      command: transport.value === "stdio" ? command.value : null,
      args: transport.value === "stdio" ? argsList() : [],
      env: transport.value === "stdio" ? pairsToRecord(envPairs.value) : {},
      url: transport.value === "http" ? url.value : null,
      bearer_token_env_var: transport.value === "http" ? bearer.value : null,
      http_headers: transport.value === "http" ? pairsToRecord(headerPairs.value) : {},
      env_http_headers: transport.value === "http" ? pairsToRecord(envHeaderPairs.value) : {},
    };
    await api.saveMcpServer(props.server?.name ?? null, spec);
    message.success("MCP 服务器已保存");
    emit("back");
  } catch (error) {
    message.error(String(error));
  } finally {
    saving.value = false;
  }
}
</script>

<template>
  <section class="apple-edit-page mx-auto flex w-full max-w-none flex-col" @keydown.ctrl.enter="save">
    <div class="apple-page-bar apple-page-bar--roomy apple-edit-toolbar apple-edit-toolbar--header">
      <button type="button" class="apple-page-header apple-back-button" aria-label="返回" @click="emit('back')">
        <PhArrowLeft class="h-4 w-4 shrink-0 text-accent" weight="bold" aria-hidden="true" />
        <span class="apple-title">{{ creating ? "新建 MCP 服务器" : "编辑 MCP 服务器" }}</span>
      </button>
    </div>

    <div class="apple-edit-content">
      <div class="apple-group shrink-0 p-0">
        <div class="apple-panel-section">
          <div class="grid gap-4 sm:grid-cols-2">
            <div>
              <div class="field-label mb-1.5">名称</div>
              <n-input v-model:value="name" maxlength="64" placeholder="例如：context7" />
              <p class="muted mt-1.5 text-xs">写入 config.toml 的 [mcp_servers.名称]，仅限字母、数字、下划线和连字符。</p>
            </div>
            <div>
              <div class="field-label mb-1.5">传输类型</div>
              <n-select v-model:value="transport" :options="transportOptions" />
            </div>
          </div>
        </div>

        <div class="apple-panel-section">
          <template v-if="transport === 'stdio'">
            <div>
              <div class="field-label mb-1.5">启动命令</div>
              <n-input v-model:value="command" class="mono" placeholder="例如：npx 或 C:\tools\server.exe" />
            </div>
            <div class="mt-4">
              <div class="field-label mb-1.5">启动参数</div>
              <n-input v-model:value="argsText" type="textarea" :rows="2" class="mono" placeholder="每行一个参数，例如：-y" />
            </div>
          </template>
          <template v-else>
            <div>
              <div class="field-label mb-1.5">服务地址</div>
              <n-input v-model:value="url" class="mono" placeholder="https://mcp.example.com/mcp" />
            </div>
            <div class="mt-4">
              <div class="field-label mb-1.5">Bearer Token 环境变量名（可选）</div>
              <n-input v-model:value="bearer" class="mono" placeholder="例如：TAVILY_API_KEY" />
              <p class="muted mt-1.5 text-xs">Codex 启动时从该环境变量读取令牌放入 Authorization 头；留空则不携带。</p>
            </div>
          </template>
        </div>

        <div class="apple-panel-section">
          <n-collapse>
            <n-collapse-item title="高级选项（环境变量 / 请求头 / 超时）" name="advanced">
              <template v-if="transport === 'stdio'">
                <div class="field-label mb-1.5">环境变量</div>
                <n-dynamic-input v-model:value="envPairs" preset="pair" key-placeholder="变量名" value-placeholder="值" :on-create="() => ({ key: '', value: '' })" />
              </template>
              <template v-else>
                <div class="field-label mb-1.5">HTTP 请求头（固定值）</div>
                <n-dynamic-input v-model:value="headerPairs" preset="pair" key-placeholder="Header 名" value-placeholder="值" :on-create="() => ({ key: '', value: '' })" />
                <div class="field-label mb-1.5 mt-4">HTTP 请求头（值取自环境变量）</div>
                <n-dynamic-input v-model:value="envHeaderPairs" preset="pair" key-placeholder="Header 名" value-placeholder="环境变量名" :on-create="() => ({ key: '', value: '' })" />
              </template>
              <div class="mt-4 grid gap-4 sm:grid-cols-2">
                <div>
                  <div class="field-label mb-1.5">启动超时（秒，可选）</div>
                  <n-input-number v-model:value="startupTimeout" class="w-full" :min="1" clearable placeholder="默认 10" />
                </div>
                <div>
                  <div class="field-label mb-1.5">工具调用超时（秒，可选）</div>
                  <n-input-number v-model:value="toolTimeout" class="w-full" :min="1" clearable placeholder="默认 60" />
                </div>
              </div>
            </n-collapse-item>
          </n-collapse>

          <p v-if="!creating" class="muted mt-3 flex items-start gap-1.5 text-xs">
            <PhInfo class="mt-0.5 h-3.5 w-3.5 shrink-0 text-accent" weight="bold" aria-hidden="true" />
            表单未涵盖的配置项（tools.*、cwd 等）与注释会原样保留；切换传输类型时仅保留当前类型的字段。
          </p>
        </div>
      </div>
    </div>

    <div class="apple-edit-toolbar apple-edit-toolbar--footer">
      <n-button secondary @click="emit('back')">取消</n-button>
      <n-button type="primary" :loading="saving" @click="save">
        <template #icon>
          <PhFloppyDisk class="h-4 w-4" weight="bold" aria-hidden="true" />
        </template>
        保存
      </n-button>
    </div>
  </section>
</template>
