// src/features/mcp/McpSyncDialog.tsx
import { useEffect, useMemo, useState } from "react";
import { AppDialog } from "../../components/AppDialog";
import type { McpSyncDiffEntry, McpSyncPreview } from "../../types";

type SyncDirection = "live-to-db" | "db-to-live";
interface McpSyncDialogProps {
  open: boolean;
  preview: McpSyncPreview | null;
  previewError: string;
  busy: boolean;
  onClose: () => void;
  onApply: (direction: SyncDirection) => void;
}

const fieldLabels: Record<string, string> = { enabled: "启用状态", startup_timeout_sec: "启动超时秒", tool_timeout_sec: "工具超时秒", command: "启动命令", args: "启动参数", env: "环境变量", url: "服务地址", bearer_token_env_var: "令牌环境变量", http_headers: "HTTP 头", env_http_headers: "环境变量 HTTP 头" };
const valueText = (value: unknown) => value === null ? "未设置" : typeof value === "string" ? value : JSON.stringify(value);
const kindText = (entry: McpSyncDiffEntry) => entry.kind === "live_only" ? "外部新增" : entry.kind === "db_only" ? "配置文件缺失" : entry.unmodeled_only ? "仅格式差异" : "内容被修改";

export default function McpSyncDialog({ open, preview, previewError, busy, onClose, onApply }: McpSyncDialogProps) {
  const [step, setStep] = useState<"diff" | "confirm">("diff");
  const [direction, setDirection] = useState<SyncDirection | null>(null);
  const [expanded, setExpanded] = useState<Set<string>>(new Set());
  useEffect(() => { if (!open) { setStep("diff"); setDirection(null); setExpanded(new Set()); } }, [open]);
  const title = step === "confirm" && direction ? direction === "db-to-live" ? "确认：数据库 → config.toml" : "确认：config.toml → 数据库" : "MCP 配置不一致";
  const entries = preview?.entries ?? [];
  const pendingLines = useMemo(() => {
    const names = (kind: McpSyncDiffEntry["kind"]) => entries.filter((entry) => entry.kind === kind).map((entry) => entry.name);
    const parts = (values: string[]) => values.flatMap((value, index) => [index ? "、" : "", <code key={value} className="mono code-tok">{value}</code>]);
    if (!direction) return [];
    if (!preview) return [<span key="rebuild">该文件当前无法解析，将用数据库中的 MCP 配置重建整个 MCP 段。</span>, <span key="backup">执行前会自动备份 <code className="mono code-tok">~/.codex/config.toml</code>。</span>];
    const added = names("live_only"); const missing = names("db_only"); const changed = names("changed");
    const lines: React.ReactNode[] = [];
    if (direction === "db-to-live") {
      if (added.length) lines.push(<span key="added" className="font-semibold text-red-600 dark:text-red-400">配置文件有新增，从配置文件中删除：{parts(added)}</span>);
      if (missing.length) lines.push(<span key="missing">配置文件缺失，写入配置文件：{parts(missing)}</span>);
      if (changed.length) lines.push(<span key="changed">配置文件已修改，恢复为数据库内容：{parts(changed)}</span>);
      lines.push(<span key="backup">执行前会自动备份 <code className="mono code-tok">~/.codex/config.toml</code>。</span>);
    } else {
      if (added.length) lines.push(<span key="added">数据库新增：{parts(added)}</span>);
      if (changed.length) lines.push(<span key="changed">数据库修改：{parts(changed)}</span>);
      if (missing.length) lines.push(<span key="missing">数据库删除：{parts(missing)}</span>);
    }
    return lines;
  }, [direction, entries, preview]);

  const requestDirection = (next: SyncDirection) => { setDirection(next); setStep("confirm"); };
  return <AppDialog open={open} onOpenChange={(next) => { if (!next && !busy) onClose(); }} title={title} className="max-w-[560px]" footer={step === "confirm" ? <div className="flex w-full items-center justify-end gap-2"><button type="button" className="apple-action-button" disabled={busy} onClick={() => setStep("diff")}>{previewError ? "返回" : "返回差异"}</button><button type="button" className="apple-action-button app-button--primary" disabled={busy || !direction} onClick={() => direction && onApply(direction)}>{direction === "db-to-live" ? "确认覆盖 config.toml" : "确认覆盖数据库"}</button></div> : <div className="w-full space-y-2"><p className="muted text-xs">箭头表示用左侧覆盖右侧；覆盖 config.toml 前会自动备份当前文件。</p><div className="grid grid-cols-[auto_minmax(0,1fr)_minmax(0,1fr)] items-center gap-2"><button type="button" className="apple-action-button shrink-0" disabled={busy} onClick={onClose}>取消</button>{!previewError ? <button type="button" className="apple-action-button" disabled={busy} onClick={() => requestDirection("db-to-live")}>数据库 → config.toml</button> : null}<button type="button" className="apple-action-button app-button--primary" disabled={busy} onClick={() => requestDirection(previewError ? "db-to-live" : "live-to-db")}>{previewError ? "数据库 → config.toml" : "config.toml → 数据库"}</button></div></div>}>
    {step === "confirm" ? <div className="space-y-3"><p className="text-sm">{direction === "db-to-live" ? previewError ? <>config.toml 无法解析，将用数据库中的 MCP 配置重建整个文件。</> : <>将用数据库中的 MCP 配置完整替换 <code className="mono code-tok">~/.codex/config.toml</code> 的 <code className="mono code-tok">[mcp_servers]</code> 段；配置文件中的其他配置不受影响。</> : <>将用 <code className="mono code-tok">~/.codex/config.toml</code> 的 <code className="mono code-tok">[mcp_servers]</code> 段完整替换数据库中的 MCP 配置；数据库中的其他数据不受影响。</>}</p><ul className="space-y-1.5 text-sm leading-relaxed">{pendingLines.map((line, index) => <li key={index}>{line}</li>)}</ul></div> : previewError ? <div className="space-y-3"><p className="muted text-sm">{previewError}</p><p className="muted text-sm"><code className="mono code-tok">config.toml</code> 当前无法解析，无法对比差异；可用数据库中的 MCP 配置覆盖恢复（写前自动备份原文件）。</p></div> : preview ? <div className="space-y-3"><div className="flex flex-wrap gap-2"><span className="apple-chip">数据库中的 MCP 配置 <strong>{preview.db_count} 台</strong></span><span className="apple-chip">config.toml 中的 MCP 配置 <strong>{preview.live_count} 台</strong></span><span className="apple-chip">差异 <strong>{preview.entries.length} 项</strong></span></div><div className="max-h-[50vh] space-y-2 overflow-y-auto pr-1">{entries.map((entry) => { const isExpanded = expanded.has(entry.name); return <div key={entry.name} className="apple-group"><button type="button" className="flex w-full items-center gap-2 bg-black/4 px-3 py-2.5 text-left transition-colors dark:bg-white/6" aria-expanded={isExpanded} onClick={() => setExpanded((current) => { const next = new Set(current); if (next.has(entry.name)) next.delete(entry.name); else next.add(entry.name); return next; })}><span className="flex min-w-0 flex-1 items-center gap-2"><span className={`apple-chip ${entry.kind === "live_only" || entry.unmodeled_only ? "chip-warn" : "chip-danger"}`}>{kindText(entry)}</span><span className="truncate font-semibold">{entry.name}</span></span><span className="muted shrink-0 text-xs">{isExpanded ? "收起" : "查看明细"}</span></button>{isExpanded ? <div className="mono space-y-1 border-t border-[var(--panel-divider)] bg-black/4 p-3 text-[11px] leading-relaxed break-all dark:bg-white/6">{entry.changed_fields.length ? entry.changed_fields.map((diff) => <div key={diff.field}>{fieldLabels[diff.field] ?? diff.field}：数据库 {valueText(diff.db)} → config.toml {valueText(diff.live)}</div>) : entry.unmodeled_only ? <p>建模字段全部相同，差异只在注释 / 格式 / 未建模键。</p> : <p className="whitespace-pre-wrap">{entry.live_toml ?? entry.db_toml}</p>}</div> : null}</div>; })}</div></div> : null}
  </AppDialog>;
}

// src/components/McpSyncDialog.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import { NButton, NModal } from "naive-ui";
import type { McpSyncDiffEntry, McpSyncPreview } from "../types";
import { mcpTransportText } from "../utils";

type SyncDirection = "live-to-db" | "db-to-live";

const props = defineProps<{
  show: boolean;
  preview: McpSyncPreview | null;
  /** live 配置无法解析时的错误文本；非空进入“仅可从数据库恢复”降级模式。 */
  previewError: string;
  busy: boolean;
}>();

const emit = defineEmits<{
  "update:show": [value: boolean];
  apply: [direction: SyncDirection];
}>();

// 展开明细的服务器名；预览数据更新后整体收起
const expandedNames = ref<Set<string>>(new Set());
watch(
  () => props.preview,
  () => {
    expandedNames.value = new Set();
  },
);

// 记录被点中的方向，只让那个按钮转 loading；同步结束后父组件把 busy 置回 false
const clickedDirection = ref<SyncDirection | null>(null);
watch(
  () => props.busy,
  (busy) => {
    if (!busy) clickedDirection.value = null;
  },
);

function toggleExpand(name: string) {
  const next = new Set(expandedNames.value);
  if (next.has(name)) {
    next.delete(name);
  } else {
    next.add(name);
  }
  expandedNames.value = next;
}

function apply(direction: SyncDirection) {
  clickedDirection.value = direction;
  emit("apply", direction);
}

function onShowChange(value: boolean) {
  if (props.busy) return;
  emit("update:show", value);
}

// 建模字段的中文名（与 Rust 侧 mcp_sync_preview 输出的字段一一对应）
const fieldLabels: Record<string, string> = {
  enabled: "启用状态",
  startup_timeout_sec: "启动超时秒",
  tool_timeout_sec: "工具超时秒",
  command: "启动命令",
  args: "启动参数",
  env: "环境变量",
  url: "服务地址",
  bearer_token_env_var: "令牌环境变量",
  http_headers: "HTTP 头",
  env_http_headers: "环境变量 HTTP 头",
};

function fieldValueText(value: unknown) {
  if (value === null) return "未设置";
  if (typeof value === "string") return value;
  return JSON.stringify(value);
}

function kindText(entry: McpSyncDiffEntry) {
  if (entry.kind === "live_only") return "仅配置文件";
  if (entry.kind === "db_only") return "仅数据库";
  return entry.unmodeled_only ? "仅格式差异" : "内容不同";
}

function kindChipClass(entry: McpSyncDiffEntry) {
  if (entry.kind === "changed" && !entry.unmodeled_only) {
    return "apple-chip chip-danger";
  }
  return "apple-chip chip-warn";
}

function transportTextOf(entry: McpSyncDiffEntry) {
  return mcpTransportText(entry.live_spec ?? entry.db_spec);
}
</script>

<template>
  <n-modal
    :show="show"
    preset="card"
    class="max-w-[560px]"
    title="MCP 同步差异"
    @update:show="onShowChange"
  >
    <!-- 降级模式：live 无法解析，无法对比，只能从数据库镜像恢复 -->
    <div v-if="previewError" class="space-y-3">
      <p class="muted text-sm">{{ previewError }}</p>
      <p class="muted text-sm">
        配置文件当前无法解析，无法对比差异；可从数据库镜像恢复（写前自动备份原文件）。
      </p>
    </div>
    <!-- 正常模式：body 只放摘要与差异列表（列表自身滚动），操作区固定在卡片 footer -->
    <div v-else-if="preview" class="space-y-3">
      <p class="muted text-sm">
        配置文件 <span class="font-semibold text-accent">{{ preview.live_count }}</span> 台 ·
        数据库镜像 <span class="font-semibold text-success">{{ preview.db_count }}</span> 台 ·
        <span class="font-semibold text-[var(--warning)]">{{ preview.entries.length }}</span>
        项差异
      </p>
      <div class="max-h-[60vh] space-y-2 overflow-y-auto pr-1">
        <div v-for="entry in preview.entries" :key="entry.name">
          <button
            type="button"
            class="apple-list-row apple-list-row--outlined w-full text-left transition-colors hover:bg-black/4 dark:hover:bg-white/6"
            @click="toggleExpand(entry.name)"
          >
            <span class="flex min-w-0 items-center gap-2">
              <span :class="kindChipClass(entry)" class="shrink-0">{{ kindText(entry) }}</span>
              <span class="truncate text-[var(--font-size-base)] font-semibold">{{ entry.name }}</span>
              <span class="shrink-0 rounded-md bg-black/5 px-1.5 py-px text-[10px] font-medium tracking-wide text-zinc-500 dark:bg-white/10 dark:text-zinc-400">
                {{ transportTextOf(entry) }}
              </span>
            </span>
            <span class="muted shrink-0 text-xs">{{ expandedNames.has(entry.name) ? "收起" : "明细" }}</span>
          </button>
          <div
            v-if="expandedNames.has(entry.name)"
            class="mono mt-1 space-y-1 rounded-[var(--radius-control-sm)] bg-black/4 p-3 text-[11px] leading-relaxed break-all dark:bg-white/6"
          >
            <div v-if="entry.changed_fields.length" class="space-y-1">
              <div v-for="diff in entry.changed_fields" :key="diff.field">
                {{ fieldLabels[diff.field] ?? diff.field }}：{{ fieldValueText(diff.live) }} →
                {{ fieldValueText(diff.db) }}
              </div>
            </div>
            <p v-else-if="entry.unmodeled_only">建模字段全部相同，差异只在注释 / 格式 / 未建模键。</p>
            <p v-else class="whitespace-pre-wrap">{{ entry.live_toml ?? entry.db_toml }}</p>
          </div>
        </div>
      </div>
    </div>

    <template #footer>
      <div class="space-y-2">
        <p v-if="!previewError" class="muted text-xs">
          选择一种方向覆盖另一侧；写回配置文件以数据库为准，更新数据库以 config.toml 为准，写回前会自动备份原文件。
        </p>
        <div class="dialog-actions grid grid-cols-[auto_minmax(0,1fr)_minmax(0,1fr)] items-center gap-2">
          <n-button class="shrink-0" :disabled="busy" @click="onShowChange(false)">取消</n-button>
          <n-button
            v-if="!previewError"
            secondary
            :disabled="busy"
            :loading="busy && clickedDirection === 'db-to-live'"
            @click="apply('db-to-live')"
          >
            写回配置文件
          </n-button>
          <n-button
            type="primary"
            :disabled="busy"
            :loading="busy && clickedDirection === 'live-to-db'"
            @click="apply(previewError ? 'db-to-live' : 'live-to-db')"
          >
            {{ previewError ? "从数据库恢复" : "更新数据库" }}
          </n-button>
        </div>
      </div>
    </template>
  </n-modal>
</template>
